### ISSUE TITLE
Agent startup error - PoolLedgerTimeout

### ISSUE THREAD

**Issue by Durai46** [yunxi-zhang/ACAPy-Controller-Angular#1]
Hi, 

Seeing an exception while executing runIssuer.sh. Is anything missing on ledger config ? 

2022-05-30 14:04:17,229 aries_cloudagent.core.profile INFO Create profile manager: indy
2022-05-30 14:04:17,233 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:127 | Worker thread started
2022-05-30 14:04:17,233 indy.libindy WARNING _indy_loop_callback: Function returned error 
2022-05-30 14:04:19,349 aries_cloudagent.indy.sdk.wallet_setup INFO Creating master secret...
2022-05-30 14:05:19,384 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:75 | OpenAck handle 4, pool_id 4, result Err(IndyError { inner: 

Pool timeout

Pool timeout })
2022-05-30 14:05:19,384 indy.libindy WARNING _indy_loop_callback: Function returned error 
2022-05-30 14:05:19,386 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
indy.error.PoolLedgerTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 96, in setup
    self.root_profile, self.setup_public_did and self.setup_public_did.did
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
    async with ledger:
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 272, in __aenter__
    await self.pool.context_open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 205, in context_open
    await self.open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
    ) from err_value
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
  Caused by: Pool timeout

Shutting down

**Comment by yunxi-zhang** [comment]
There is nothing wrong with the frontend app itself based on this issue. The issue you have occurs when your agent is trying to connect to an Indy network. The shell file uses Sovrin BuilderNet by default, so can you confirm if your environment is allowed all traffic out to Sovrin BuilderNet?

**Comment by Durai46** [comment]
I was able run the 3 agents with "--no-ledger" options, but not with the actual genesis-url.

--genesis-url  https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis \
--seed La3QE23tejV7x9gAj63UrDft2ThQoMj0  \


_Logs:_

acapy % ./runIssuer.sh
issuer
issuer
2022-06-02 08:22:12,293 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis
2022-06-02 08:22:13,640 aries_cloudagent.core.profile INFO Create profile manager: indy
2022-06-02 08:22:13,646 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:127 | Worker thread started
2022-06-02 08:22:13,647 indy.libindy WARNING _indy_loop_callback: Function returned error 
2022-06-02 08:22:15,597 aries_cloudagent.indy.sdk.wallet_setup INFO Creating master secret...
2022-06-02 08:23:15,612 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:75 | OpenAck handle 4, pool_id 4, result Err(IndyError { inner: 

Pool timeout

Pool timeout })
2022-06-02 08:23:15,613 indy.libindy WARNING _indy_loop_callback: Function returned error 
2022-06-02 08:23:15,614 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
indy.error.PoolLedgerTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 96, in setup
    self.root_profile, self.setup_public_did and self.setup_public_did.did
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
    async with ledger:
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 272, in __aenter__
    await self.pool.context_open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 205, in context_open
    await self.open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
    ) from err_value
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
    self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
  Caused by: Pool timeout


Shutting down

**Comment by yunxi-zhang** [comment]
Great, this means your agents can communicate via your local docker network. Think the issue does come from your agent can't connect to Sovrin Network. Please make sure your local network is allowed all traffic to the Internet via port range: 9700 - 9799. Port ranges could be blocked in company's network, please test it in a home network, that should work. I'll close this ticket as there's nothing wrong with the shell script itself.
